### ISSUE TITLE
Provide d3-jetpack via npm

### ISSUE THREAD

**Issue by yonester** [gka/d3-jetpack#10]
Although d3 is mostly a frontend library, many developers use npm with browserify or simply build scripts to install frontend libraries. Case-in-point... d3!

It would be very helpful if d3-jetpack did the same so we can retrieve it via `npm install d3-jetpack`.

**Comment by yonester** [comment]
Really all you need is the `package.json` file so we can retrieve it directly from Github. If you want to make it even easier, you can also [publish it](https://docs.npmjs.com/getting-started/publishing-npm-packages).

**Comment by gka** [comment]
agree. saw that someone made a package already, trying to get access so I can update the package.json. the current one is missing the `main` script definition.

but then it should be easy to use in node:

```js
var jsdom = require('jsdom-global');

jsdom(function () {
    var d3 = require('d3');
    require('d3-jetpack')(d3);

    d3.select('body').append('div#testId.test-class');
    console.log(d3.select('body').html());
});
```

**Comment by gka** [comment]
the current `d3-jetpack` version is now on npm

```js
var d3 = require('d3');
require('d3-jetpack');

console.log(d3.ascendingKey); // [Function]
```
