### ISSUE TITLE
ƒ ?

### ISSUE THREAD

**Issue by nise** [gka/d3-jetpack#22]
Why is there a non-standard ascii-symbol used inside the code?

Firefox complains about it. Programmers on the other hand, get struggle to finde the symbol on their keyboard. 

I replaced ƒ by f, which makes it easier.

**Comment by 1wheel** [comment]
I use it quite a lot inside of other function calls so only taking up on character is nice. 

Adding a single letter variable name to the global name space is a little rude/risky, so `ƒ` is used to reduce the likelihood of collision. As the readme notes, you can also use `d3.f`.
