### ISSUE TITLE
Jetpack insert is breaking d3

### ISSUE THREAD

**Issue by luiscarli** [gka/d3-jetpack#30]
```
<!DOCTYPE html>
<meta charset="utf-8">
<style>

body {
  font: 14px sans-serif;
}

</style>
<body>
<script src="//d3js.org/d3.v4.min.js"></script>
<script src="//unpkg.com/d3-jetpack@2.0.0"></script>
<script>

var c = d3.conventions()
c.drawAxis()

</script>
```

![screen shot 2017-03-31 at 1 32 15 pm](https://cloud.githubusercontent.com/assets/1903248/24561888/9016d032-1616-11e7-8290-3e35cfe6e778.png)

Same error when using only `d3v4+jetpack.js`

**Comment by jgrecoarroyo** [comment]
I have the exact same error, even without using the `d3.conventions`, but when trying to draw an axis.

**Comment by luiscarli** [comment]
the stack trace points to the d3.insert prototype override that jetpack does.

**Comment by 1wheel** [comment]
Whoops! That's what we get for porting over old functions without adding tests - thanks for the heads up.
