### ISSUE TITLE
Neither .st() nor .at() work after .transition().duration(time)

### ISSUE THREAD

**Issue by beemyfriend** [gka/d3-jetpack#33]
Neither `.st()` nor `.at()` work after `.transition().duration(time)`. However both `.styles()` and `.attrs()` work after transition.

For example, the below code does not work:

    <--! I'm using a local copy of jetpack that i downloaded  about a month ago -->

    <script src = 'd3v4+jetpack.js'> 
      var svg = d3.select('body').append('svg').at({width: 1000, height: 1000});

      var newDim = {hw: 500, fill: 'purple', stroke: 'yellow'};

      svg.append('rect#reproduction')
        .at({height: newDim.hw, width: newDim.hw})
        .st({fill: newDim.fill, stroke: newDim.stroke, 'stroke-width': 5})
        .on('click', change);
  
      function change(){
                newDim.hw == 900 ? newDim = {hw: 500, fill: 'purple', stroke: 'yellow'} : newDim = {hw: 900, fill: 'yellow', stroke: 'purple'};
            
                svg.selectAll('rect#reproduction')
                  .transition().duration(500)
                  .at({height: newDim.hw, width: newDim.hw})
                  .st({fill: newDim.fill, stroke: newDim.stroke});
      }
    </script>`  

However, the code does work once you change the post transition `.at()` and `.st()` to `.attrs()` and `.styles()`. I'm not sure if this is a big deal, but i thought I'd bring it to your attention.

**Comment by 1wheel** [comment]
Could you try grabbing the current version?

`transition.st` is working for me here: https://github.com/gka/d3-jetpack/blob/master/test/index.html#L82-L85

**Comment by beemyfriend** [comment]
You're right, my local copy was outdated. I should have checked before bothering you. Thanks!
