### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by rezpe** [gka/d3-jetpack#34]
Hi,

   What happens when the scale in conventions need to use a category instead of a measure (using another scale instead of a linear scale) ? Is there an option for this ?

Regards,
Rezpe

**Comment by 1wheel** [comment]
You can replace the provided `c.x` with anything you want. For instance:

```
var xLogScale = d3.scaleLog().domain([1, 1000]).range(c.x.range())
```

If you still want to use `c.drawAxis`, pass the new scale to `c.xAxis`:

```
c.xAxis.scale(xLogScale)`
c.drawAxis() // draws log axis
```

**Comment by rezpe** [comment]
Awesome, 
Thx !!!!!
