### ISSUE TITLE
Github release for 2.0.7

### ISSUE THREAD

**Issue by timelyportfolio** [gka/d3-jetpack#37]
Hi, do you plan to add a Github release for `2.0.7`?  It appears `1.0.6` is the last tagged.  Thanks so much for the fantastic and helpful work.  For reference, we are including in the R package `d3r` (see [pull](https://github.com/gka/d3-jetpack/releases)), and we would like to test to insure that we are on the current release.

**Comment by 1wheel** [comment]
Added! 

https://github.com/gka/d3-jetpack/releases/tag/v2.0.8
