### ISSUE TITLE
Include license information

### ISSUE THREAD

**Issue by shunchu** [gka/d3-jetpack#4]
You should consider including license information (MIT, BSD, Apache2... etc) to help minimize friction for developers who wish to leverage your wonderful library in an environment where things like that matter (enterprise... etc).

**Comment by axelson** [comment]
+1 this looks really interesting but I cannot use it if it doesn't specify a license.

**Comment by axelson** [comment]
This can be closed since there's a license now: https://github.com/gka/d3-jetpack/blob/master/COPYING
