### ISSUE TITLE
api tweaks

### ISSUE THREAD

**Issue by 1wheel** [gka/d3-jetpack#44]
Can leave the old functions in while updating the docs and adding new aliases. 

### parentSel

I usually do `var sel = d3.select('.graph').html()` at the start of my render function. `d3.conventions({sel})` is cleaner than `d3.conventions({parentSel: sel})`.
### appendMany 

I think `dataAppend` is easier to teach; the first argument is the `data`, the second is what you're `append`ing. Or `manyAppend`? 

### ƒ

Not sure this is necessary anymore with ES6. Maybe remove from the examples?

**Comment by 1wheel** [comment]
Maybe `arrayAppend`?

**Comment by gka** [comment]
how about just `appendMany("div", data)` ?

**Comment by gka** [comment]
for a grace period we could add in some code that detects whether the string argument is first or second and output a `console.warning("DEPRECATED: jetpack's appendMany order of arguments has changed. it's appendMany("div", data) now");`
