### ISSUE TITLE
Switching to selectAppend in conventions?

### ISSUE THREAD

**Issue by nstrayer** [gka/d3-jetpack#49]
I find myself wanting to encapsulate my entire viz into a single function which is made massively easier by `selectAppend` (thank you so much for saving me from writing my own ugly version another time) but have found the process of resetting the svg/scales to be awkward with conventions. Would there be interest in replacing the [`append('svg')`](https://github.com/gka/d3-jetpack/blob/master/src/conventions.js#L38) with a `selectAppend` to allow for easy resizing? 
I may be incorrect in my decision to put the SVG setup into the big draw. It seems like the best way to do it currently is something along the lines of 
```js
onResize = () => {
  const newWidth = getNewWidth();
  const newHeight = getNewHeight();
  c.svg.parent().at(...);
  // update scale ranges and reset the main g-container
  drawViz(c);
}
```
Which feels... not right. With `selectAppend` it seems it could be as easy as putting `const c_new = d3.convention(...)` inside `drawViz()`. 

This is asked with the idea of, if desired, I can submit a PR but I wanted to see if it was in keeping with the ethos of d3-jetpack.

**Comment by 1wheel** [comment]
Typically I blow away the entire chart on resize:

    function drawChart(){
      var sel = d3.select('.g-speed-path').html('')
      var c = d3.conventions({sel})

      ...
    }

    drawChart()
    d3.select(window).on('resize', _.debounce(drawChart, 100))

As long as the resizing is debounced, I don't think there's a huge benefit to mutating the existing DOM elements to the new size. Most users don't resize and when they do the code should only get called once or twice.  

Also: after adding `layers`, I'm not sure that the `selectAppend` implementation would be simple. Possible to add two SVGs now!

**Comment by nstrayer** [comment]
Ah, this makes sense. I like it. Thanks!
