### ISSUE TITLE
SVG element has position:absolute. Why?

### ISSUE THREAD

**Issue by janwillemtulp** [gka/d3-jetpack#52]
The SVG element that is created in the constructor has a style property `position: 'absolute'`. Why? Currently this messes up my design, and I have to disable it explicitly. It would be great if this would be removed, and if you want it, you can set it yourself.

**Comment by 1wheel** [comment]
I added it to support [stacking different divs](https://bl.ocks.org/1wheel/f9b9909f10ed0f01780c5338ad38bd50). 

Maybe it should be disabled if you're not passing in `layers`, along with a note in the docs explaining that `layers` also sets `position: 'absolute'`. 

Sorry about all the rough edges! Thanks for the bug reports.

**Comment by janwillemtulp** [comment]
No problem! The workaround was easy! :)
