### ISSUE TITLE
Namespaced timers

### ISSUE THREAD

**Issue by 1wheel** [gka/d3-jetpack#55]
@gka thoughts on this? https://github.com/d3/d3-timer/issues/30

Not sure if we should monkey patch `timer`, `interval` and `timeout`: 

```
var oldD3Interval = exports.interval
var prevIntervals = {}
exports.interval = function(fn, delay, time, name){
  if (prevIntervals[name]) prevIntervals[name].stop()

  var interval = oldD3Interval(fn, delay, time, name)
  if (name) prevIntervals[name] = interval
  
  return interval
}
```

Or make new functions `timerNS`, `intervalNS`, `timeoutNS`

**Comment by gka** [comment]
I'm all for monkey patching ;-) 
all we're doing is adding a parameter to the end?

**Comment by 1wheel** [comment]
yup
