### ISSUE TITLE
How about d3.indexBy(array, key)

### ISSUE THREAD

**Issue by gka** [gka/d3-jetpack#59]
Identical behaviour as in [_.indexBy](http://underscorejs.org/#indexBy).

```js
var indexed = d3.nest()
  .key(d => d.FIPS)
  .rollup(values => values[0])
  .object(data);
```
would become
```js
var indexed = d3.indexBy(data, d => d.FIPS);
```

**Comment by 1wheel** [comment]
I'm ambivalent. 

I usually include underscore so wouldn't use this too much. And where do we draw the line on which underscore functions not to include?

On the other hand, I basically only use `_.indexBy`, `_.min`, `_.sortBy` and `_.debounce`...

**Comment by gka** [comment]
agreed. let's keep using underscore
